### ISSUE TITLE
Example code not working?

### ISSUE THREAD

**Issue by RazgrizOne** [daisuke-t-jp/xxHash-Swift#1]
I am not sure if I am missing something, but I can't get the example code to work for the life of me. I guess I am supposed to use length instead of count, but then I also cannot access the subscript of the NSData type. On the off chance that its an issue with the example code I am posting it here, but assistance would be appreciated if it is just me not understanding the code.

![screen shot 2019-03-06 at 4 53 24 pm](https://user-images.githubusercontent.com/10679161/53916532-5c244700-4030-11e9-92fb-07f8bfc02d51.png)

**Comment by daisuke-t-jp** [comment]
Hi,

Thanks for your report.

You probably looked code in [README.md](https://github.com/daisuke-t-jp/xxHash-Swift/blob/46a2f32ff5ce36dc2d58f5060622fb273a50bc4b/README.md).
and It was broken code.

I fixed [README.md(commit)](https://github.com/daisuke-t-jp/xxHash-Swift/commit/b8090b9f56e7e66f7804597644fb76a2b49111d4#diff-04c6e90faac2675aa89e2176d2eec7d8).

```swift
let data = NSData(contentsOfFile: path) // Before(NG)
let data = NSData(contentsOfFile: path)! as Data // After(OK)
```
Will the build succeed this time?

Regards.

**Comment by RazgrizOne** [comment]
Appreciate it, I will try this soon and let you know how it goes.

Thanks for doing the legwork for this, it will be useful for my project.

**Comment by RazgrizOne** [comment]
let path = bundle.path(forResource: "alice29", ofType: "txt")!

Won't find it if you install using CocoaPods, but other than that it works great! Thanks for your assistance and I consider this issue solved.
