### ISSUE TITLE
Swift Package Manager ?

### ISSUE THREAD

**Issue by vexy** [daisuke-t-jp/xxHash-Swift#6]
Would be very handy to have SPM installation option as well (specially these days).

If needed, I can help with setting up `Package.swift` file.

**Comment by daisuke-t-jp** [comment]
@vexy 
Hi,

Package.swift exists in the project.
https://github.com/daisuke-t-jp/xxHash-Swift/blob/master/Package.swift

I was able to confirm that xxHash can be installed via SwiftPackageManager in Xcode15.4.

What do you need?

**Comment by vexy** [comment]
Seems like I need better glasses 👓😄

Feel free to close this "issue" as everything is okay actually.

**Comment by RazgrizOne** [comment]
Long time ago now, but I appreciate that you are still active. Thanks for
your work and I hope you are doing well.

**Comment by RazgrizOne** [comment]
And I am confused as well it seems. disregard. 😆
